services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - './user-service/infrastructure/db/initdb.sql:/docker-entrypoint-initdb.d/init-user-service-db.sql'
      - './account-service/infrastructure/db/initdb.sql:/docker-entrypoint-initdb.d/init-account-service-db.sql'

  pgadmin:
    image: 'dpage/pgadmin4:7.6'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=noemail@noemail.org'
      - 'PGADMIN_DEFAULT_PASSWORD=postgres'
      - 'PGADMIN_LISTEN_PORT=5433'
    ports:
      - '5433:5433'
    depends_on:
      - postgres

  rabbitmq:
    image: 'rabbitmq:3.12.4'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=rabbitmq'
      - 'RABBITMQ_DEFAULT_USER=rabbitmq'
    ports:
      - '5672:5672'

  nginx:
    image: 'nginx:1.25.2'
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - user-service
      - account-service

  user-service:
    build: user-service
    ports:
      - '8081:8081'
    depends_on:
      - postgres
      - rabbitmq

  account-service:
    build: account-service
    ports:
      - '8082:8082'
    depends_on:
      - postgres
      - rabbitmq